# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='bg_img_url',
            field=models.CharField(max_length=100, verbose_name='background image url'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='bg_color',
            field=models.CharField(max_length=20, verbose_name='background color'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_url',
            field=models.CharField(max_length=100, verbose_name='icon url'),
        ),
    ]
