# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20171119_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(auto_now=True),
        ),
    ]
