# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_project_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
